info:
  contact: {}
paths:
  /index:
    get:
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取首页
      tags:
      - 首页
  /user/createUser:
    get:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 确认密码
        in: query
        name: repassword
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      tags:
      - 用户相关接口
  /user/getUserList:
    get:
      description: 首页
      produces:
      - application/json
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      tags:
      - 用户相关接口
  /user/updateUser:
    post:
      parameters:
      - description: id
        in: formData
        name: id
        type: string
      - description: 密码
        in: formData
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      tags:
      - 用户相关接口
swagger: "2.0"
